name:                miniwhile
version:             0.1.0.0
github:              "basilz/miniwhile"
license:             BSD3
author:              "Andrea Basile"
maintainer:          "example@example.com"
copyright:           "2023 Andrea Basile"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/miniwhile#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- parsec
- text-show

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  exposed-modules: MiniWhile
  source-dirs: src

executables:
  miniwhile-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - miniwhile

tests:
  miniwhile-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - miniwhile
    - hspec
    - hedgehog
